### ISSUE TITLE
The Unix Way

### ISSUE THREAD

**Issue by jtgd** [zhangkaizhao/remove_empty_subdirs#2]
Does your program have a different effect than:

    find -depth -type d -empty -print -exec rmdir {} \;

**Comment by zhangkaizhao** [comment]
Hi @jtgd . Thanks for noticing this unremarkable library.
The Unix Way is great and worth learning!

The main goal of this piece of code is to be used as a library on most platforms, sharing the benefit from the Rust programming language. And the command line utility is just a simple example.

It comes from my first hands-on project which developed in the Rust programming language too:
https://github.com/zhangkaizhao/repos/commit/398693cad5dc1c710033dd35d08af54c75af6c62

**Comment by jtgd** [comment]
Yes, libraries are good. They provide the Lego blocks from which we can build bigger applications. The Unix Way.
